application:
  port: 8000
  host: 0.0.0.0
  hmac_secret: "long-and-very-secret-random-key-needed-to-verify-msg-integrity"
  # note: need to set `APP_APPLICATION__HMAC_SECRET` env variable re: DigitalOcean prod
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my-sweet-secret-token"
  timeout_milliseconds: 10000
